name: Deploy to S3

on:
  push:
    branches:
      - main

env: 
  AWS_S3_BUCKET_STATIC: 'gabs-upload-widget-web-static'
  AWS_S3_BUCKET_CDN: 'gabs-upload-widget-web-cdn'
  SOURCE_DIST: './dist'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup node
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        id: install-dependencies
        run: |
          npm install
      
      - name: Build app
        id: build-app
        run: |
          npm run build

      - name: Configure AWS credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Sync files to S3 static
        id: sync-files-to-S3-static
        run: |
          aws s3 sync ${{ env.SOURCE_DIST}} s3://${{ env.AWS_S3_BUCKET_STATIC }}/ --delete

      - name: Sync files to S3 cdn
        id: sync-files-to-S3-cdn
        run: |
          aws s3 sync ${{ env.SOURCE_DIST}} s3://${{ env.AWS_S3_BUCKET_CDN }}/ --delete

      - name: Invalidate CDN cache
        id: invalidate-cdn-cache
        run: |
          aws cloudfront create-invalidation --distribuition-id ${{ secrets.CLOUDFLARE_DISTRIBUTION_ID }} --paths "/*" 
 

